export const UPLOAD_IMAGE_MAX_SIZE_MB = 10
export const UPLOAD_VIDEO_MAX_SIZE_MB = 512

export const UPLOAD_IMAGE_MAX_SIZE_BYTES = UPLOAD_IMAGE_MAX_SIZE_MB * 1024 * 1024
export const UPLOAD_VIDEO_MAX_SIZE_BYTES = UPLOAD_VIDEO_MAX_SIZE_MB * 1024 * 1024

export const UPLOAD_REQUEST_TIMEOUT_MS = 10 * 60 * 1000
